# Generated by Django 4.0.3 on 2022-03-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='employee',
            new_name='employees',
        ),
    ]
